Add handling of missing jq dependency
PelionIoT/pelion-edge-ready-test-suite pull request #17
Opened 2023-08-17 08:07 UTC by JanneKiiskila

We do require jq to operatore, document and check for it.

2023-08-23 10:52 UTC, tulsivanol approved these changes
LGTM 🚀

2023-09-01 09:29 UTC, petedyerarm requested changes
The `set -e` in perts.sh means that if the test fails the script will exit and not perform the cleanup actions. This will "leave credentials floating about"
I suggest moving the cleanup code into a trap handler function.

2023-09-03 05:51 UTC, jenia81 approved these changes

2023-09-04 12:32 UTC, tulsivanol approved these changes

2023-09-04 12:36 UTC, petedyerarm approved these changes
LGTM

2023-09-04 13:45 UTC, merged